config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :articles
  
  resources :articles do
      resources :comments
      end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

def new
@article = Article.new
  end

def index
    @articles = Article.all
end

def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end

def edit
  @article = Article.find(params[:id])
end


def show
    @article = Article.find(params[:id])
end


def article_params
    params.require(:article).permit(:title, :text)
end





end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroyse
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    
    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>HAOZHOU BLOG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- The main CSS file -->
        <link href="../app/assets/stylesheets/main.css" rel="stylesheet">

        <!-- CSS file for your custom modifications -->
        <link href="css/custom.css" rel="stylesheet">

        <link rel="shortcut icon" href="app/assets/images/favicon.ico">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target=".main-nav" data-offset="73">
<div id="parallax"></div>

<section id="header">

        <nav class="navbar navbar-fixed-top" role="navigation">

            <div class="navbar-inner">
                <div class="container">

                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#navigation"></button>

                    <!-- Logo goes here - replace the image with yours -->
                    <a href="/" class="navbar-brand"><img src="/images/rainbow.jpg" class="logo-img img-responsive" alt="HAOZHOU Blog" title="HAOZHOU! Logo"></a>


                    <div class="collapse navbar-collapse main-nav" id="navigation">

                        <ul class="nav pull-right">
                            <!-- Menu items go here -->
                            <li class="active hidden"><a href="#index">Home</a></li>
                            <li><%= link_to 'My Blog', controller: 'articles' %></li>
			    <li><%= link_to 'New article', new_article_path %></li>
                        </ul>

                    </div><!-- /nav-collapse -->
                </div><!-- /container -->
            </div><!-- /navbar-inner -->
        </nav>

    </section>

    <!--//////////////////////////////////////// end NAVIGATION BAR ////////////////////////////////////////-->


<!--/////////////////////////////////////// HERO SECTION ////////////////////////////////////////-->

    <section id="hero">

        <div class="container">
            <div class="row">

                <div class="col-md-6 intro">
                    <img src="/images/rainbow.jpg" alt="HAOZHOU BLOG" title="HAOZHOU BLOG" height="200px">
                    <p class="lead">Hey bro, what's up!</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--///////////////////////////////////////////////// end HERO SECTION ////////////////////////////////////////-->

<section id="blog">
	<div class="container">
	<div class="col-md-8 main-column">
		<div class="blog-item">
     			<div class="blog-main">


<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>


		</div>

		
	</div>
	</div>
</section>

</br></br></br>
<!--//////////////////////////////////////// FOOTER SECTION ////////////////////////////////////////-->
    <section id="footer">
        <div class="bottom-menu-inverse">

            <div class="container">

                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright &copy; 2018 Haozhou ZHANG.</p>
                    </div>

                    
                </div>
            
            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--//////////////////////////////////////// end FOOTER SECTION ////////////////////////////////////////-->

app/views/articles/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>HAOZHOU BLOG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- The main CSS file -->
        <link href="../app/assets/stylesheets/main.css" rel="stylesheet">

        <!-- CSS file for your custom modifications -->
        <link href="css/custom.css" rel="stylesheet">

        <link rel="shortcut icon" href="app/assets/images/favicon.ico">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target=".main-nav" data-offset="73">
<div id="parallax"></div>

<section id="header">

        <nav class="navbar navbar-fixed-top" role="navigation">

            <div class="navbar-inner">
                <div class="container">

                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#navigation"></button>

                    <!-- Logo goes here - replace the image with yours -->
                    <a href="/" class="navbar-brand"><img src="/images/rainbow.jpg" class="logo-img img-responsive" alt="HAOZHOU Blog" title="HAOZHOU! Logo"></a>


                    <div class="collapse navbar-collapse main-nav" id="navigation">

                        <ul class="nav pull-right">
                            <!-- Menu items go here -->
                            <li class="active hidden"><a href="#index">Home</a></li>
                            <li><%= link_to 'My Blog', controller: 'articles' %></li>
			    <li><%= link_to 'New article', new_article_path %></li>
                        </ul>

                    </div><!-- /nav-collapse -->
                </div><!-- /container -->
            </div><!-- /navbar-inner -->
        </nav>

    </section>

    <!--//////////////////////////////////////// end NAVIGATION BAR ////////////////////////////////////////-->


<!--/////////////////////////////////////// HERO SECTION ////////////////////////////////////////-->

    <section id="hero">

        <div class="container">
            <div class="row">

                <div class="col-md-6 intro">
                    <img src="/images/rainbow.jpg" alt="HAOZHOU BLOG" title="HAOZHOU BLOG" height="200px">
                    <p class="lead">Hey bro, what's up!</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--///////////////////////////////////////////////// end HERO SECTION ////////////////////////////////////////-->


<div class="container">
<h1>Listing articles</h1>
 
<%= link_to 'New article', new_article_path %>

<table id="articles">
  <tr class="alt">
    <th>Title</th>
    <th>Text</th>
    <th></th><th></th><th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr class="alt">
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


</div>

</br></br></br>
<!--//////////////////////////////////////// FOOTER SECTION ////////////////////////////////////////-->
    <section id="footer">
        <div class="bottom-menu-inverse">

            <div class="container">

                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright &copy; 2018 Haozhou ZHANG.</p>
                    </div>

                    
                </div>
            
            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--//////////////////////////////////////// end FOOTER SECTION ////////////////////////////////////////-->

app/views/articles/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>HAOZHOU BLOG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- The main CSS file -->
        <link href="../app/assets/stylesheets/main.css" rel="stylesheet">

        <!-- CSS file for your custom modifications -->
        <link href="css/custom.css" rel="stylesheet">

        <link rel="shortcut icon" href="app/assets/images/favicon.ico">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target=".main-nav" data-offset="73">
<div id="parallax"></div>

<section id="header">

        <nav class="navbar navbar-fixed-top" role="navigation">

            <div class="navbar-inner">
                <div class="container">

                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#navigation"></button>

                    <!-- Logo goes here - replace the image with yours -->
                    <a href="/" class="navbar-brand"><img src="/images/rainbow.jpg" class="logo-img img-responsive" alt="HAOZHOU Blog" title="HAOZHOU! Logo"></a>


                    <div class="collapse navbar-collapse main-nav" id="navigation">

                        <ul class="nav pull-right">
                            <!-- Menu items go here -->
                            <li class="active hidden"><a href="#index">Home</a></li>
                            <li><%= link_to 'My Blog', controller: 'articles' %></li>
			    <li><%= link_to 'New article', new_article_path %></li>
                        </ul>

                    </div><!-- /nav-collapse -->
                </div><!-- /container -->
            </div><!-- /navbar-inner -->
        </nav>

    </section>

    <!--//////////////////////////////////////// end NAVIGATION BAR ////////////////////////////////////////-->


<!--/////////////////////////////////////// HERO SECTION ////////////////////////////////////////-->

    <section id="hero">

        <div class="container">
            <div class="row">

                <div class="col-md-6 intro">
                    <img src="/images/rainbow.jpg" alt="HAOZHOU BLOG" title="HAOZHOU BLOG" height="200px">
                    <p class="lead">Hey bro, what's up!</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--///////////////////////////////////////////////// end HERO SECTION ////////////////////////////////////////-->

<section id="blog">
	<div class="container">
	<div class="col-md-8 main-column">
		<div class="blog-item">
     			<div class="blog-main">
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

		</div>

		
	</div>
	</div>
</section>

</br></br></br>
<!--//////////////////////////////////////// FOOTER SECTION ////////////////////////////////////////-->
    <section id="footer">
        <div class="bottom-menu-inverse">

            <div class="container">

                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright &copy; 2018 Haozhou ZHANG.</p>
                    </div>

                    
                </div>
            
            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--//////////////////////////////////////// end FOOTER SECTION ////////////////////////////////////////-->

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>HAOZHOU BLOG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- The main CSS file -->
        <link href="../app/assets/stylesheets/main.css" rel="stylesheet">

        <!-- CSS file for your custom modifications -->
        <link href="css/custom.css" rel="stylesheet">

        <link rel="shortcut icon" href="app/assets/images/favicon.ico">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target=".main-nav" data-offset="73">
<div id="parallax"></div>

<section id="header">

        <nav class="navbar navbar-fixed-top" role="navigation">

            <div class="navbar-inner">
                <div class="container">

                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#navigation"></button>

                    <!-- Logo goes here - replace the image with yours -->
                    <a href="/" class="navbar-brand"><img src="/images/rainbow.jpg" class="logo-img img-responsive" alt="HAOZHOU Blog" title="HAOZHOU! Logo"></a>


                    <div class="collapse navbar-collapse main-nav" id="navigation">

                        <ul class="nav pull-right">
                            <!-- Menu items go here -->
                            <li class="active hidden"><a href="#index">Home</a></li>
                            <li><%= link_to 'My Blog', controller: 'articles' %></li>
			    <li><%= link_to 'New article', new_article_path %></li>
                        </ul>

                    </div><!-- /nav-collapse -->
                </div><!-- /container -->
            </div><!-- /navbar-inner -->
        </nav>

    </section>

    <!--//////////////////////////////////////// end NAVIGATION BAR ////////////////////////////////////////-->


<!--/////////////////////////////////////// HERO SECTION ////////////////////////////////////////-->

    <section id="hero">

        <div class="container">
            <div class="row">

                <div class="col-md-6 intro">
                    <img src="/images/rainbow.jpg" alt="HAOZHOU BLOG" title="HAOZHOU BLOG" height="200px">
                    <p class="lead">Hey bro, what's up!</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--///////////////////////////////////////////////// end HERO SECTION ////////////////////////////////////////-->

<!--/////////////////////////////////////// BLOG SECTION ////////////////////////////////////////-->

<section id="blog">
	<div class="container">
	<div class="col-md-8 main-column">
		<div class="blog-item">
     			<div class="blog-main">

				<a href="#" class="blog-title"><%= @article.title %></a>
 
				<p> <%= @article.text %> </p>
 

			</div> <!-- /blog-main -->
			

			<!--/// COMMENTS SECTION ///-->
                        <h3>Comments</h3>
				<ul class="comments">
					<%= render @article.comments %>
 				</ul>
			<!--/// COMMENTS SECTION END ///-->

			
			



				<h2>Add a comment:</h2>
				<%= render 'comments/form' %>
 
				<%= link_to 'Edit', edit_article_path(@article) %> |
				<%= link_to 'Back', articles_path %>

		</div>

		
	</div>
	</div>
</section>
<!--//////////////////////////////////////// END BLOG SECTION ////////////////////////////////////////-->


</br></br></br>
<!--//////////////////////////////////////// FOOTER SECTION ////////////////////////////////////////-->
    <section id="footer">
        <div class="bottom-menu-inverse">

            <div class="container">

                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright &copy; 2018 Haozhou ZHANG.</p>
                    </div>

                    
                </div>
            
            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--//////////////////////////////////////// end FOOTER SECTION ////////////////////////////////////////-->

app/views/comments/_comment.html.erb
<li>
<div class="row">
	<div class="col-xs-9 col-md-10">
		<div class="comment-info">
			
			<p>Commenter:<%= comment.commenter %></p>
		</div>
		<div class="comment-text">
			<p><%= comment.body %></p>
		</div>
		<div class="action">
     			<button type="button" class="btn btn-danger btn-xs" title="edit">
			<%= link_to 'Destroy Comment', [comment.article, comment], method: :delete,
               data: { confirm: 'Are you sure?' } %>
      			</button>
		</div> 
</div>

</li>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>HAOZHOU BLOG</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- The main CSS file -->
        <link href="../app/assets/stylesheets/main.css" rel="stylesheet">

        <!-- CSS file for your custom modifications -->
        <link href="css/custom.css" rel="stylesheet">

        <link rel="shortcut icon" href="app/assets/images/favicon.ico">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="js/html5shiv.js"></script>
        <![endif]-->
</head>

<body id="home" data-spy="scroll" data-target=".main-nav" data-offset="73">
<div id="parallax"></div>


<section id="header">

        <nav class="navbar navbar-fixed-top" role="navigation">

            <div class="navbar-inner">
                <div class="container">

                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#navigation"></button>

                    <!-- Logo goes here - replace the image with yours -->
                    <a href="/" class="navbar-brand"><img src="/images/rainbow.jpg" class="logo-img img-responsive" alt="HAOZHOU Blog" title="HAOZHOU! Logo"></a>


                    <div class="collapse navbar-collapse main-nav" id="navigation">

                        <ul class="nav pull-right">
                            <!-- Menu items go here -->
                            <li class="active hidden"><a href="#index">Home</a></li>
                            <li><%= link_to 'My Blog', controller: 'articles' %></li>
			    <li><%= link_to 'New article', new_article_path %></li>
                        </ul>

                    </div><!-- /nav-collapse -->
                </div><!-- /container -->
            </div><!-- /navbar-inner -->
        </nav>

    </section>

    <!--//////////////////////////////////////// end NAVIGATION BAR ////////////////////////////////////////-->

<!--/////////////////////////////////////// HERO SECTION ////////////////////////////////////////-->

    <section id="hero">

        <div class="container">
            <div class="row">

                <div class="col-md-6 intro">
                    <img src="/images/rainbow.jpg" alt="HAOZHOU BLOG" title="HAOZHOU BLOG" height="200px">
                    <p class="lead">Hey bro, what's up!</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--///////////////////////////////////////////////// end HERO SECTION ////////////////////////////////////////-->


<!--/////////////////////////////////////// FEATURES SECTION ////////////////////////////////////////-->

    <section id="features">

        <div class="container">

            <header>
                <h1>Features</h1>
                <p class="lead">Write down something about your life:)</p>
            </header>

            <div class="row">
                
                <!-- Feature Item 1 -->
                <div class="col-md-4 text-center">
                    <div class="feature-icon">
			<a href="/articles/new">
                        <img src="images/pencil.jpg" alt="" title="" />
			</a>
                    </div>
                    <h4><%= link_to 'Write new blog', controller: 'articles' %></h4>
                    <p>Create new article on one click.</p>
                </div>

                <!-- Feature Item 2 -->
                <div class="col-md-4 text-center">

                    <div class="feature-icon">
                        <a href="/articles">
			<img src="images/folder.gif" href="/articles" alt="" title="" />
			</a>
                    </div>

                    <h4><%= link_to 'All your articles', controller: 'articles' %></h4>
                    <p>Read and re-edit all your articles on one click.</p>
                </div>

                <!-- Feature Item 3 -->
                <div class="col-md-4 text-center">
                    <div class="feature-icon">
                        <img src="images/comment.png" alt="" title="" />
                    </div>
                    <h4>Comment other's articles</h4>
                    <p>Visit other people's blog and give your comment.</p>
                </div>

            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--/////////////////////////////////////// end FEATURES SECTION ////////////////////////////////////////-->



<!--//////////////////////////////////////// FOOTER SECTION ////////////////////////////////////////-->
    <section id="footer">
        <div class="bottom-menu-inverse">

            <div class="container">

                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright &copy; 2018 Haozhou ZHANG.</p>
                    </div>

                    
                </div>
            
            </div><!-- /row -->
        </div><!-- /container -->

    </section>

    <!--//////////////////////////////////////// end FOOTER SECTION ////////////////////////////////////////-->
</body>
</html>